print('==== desafio 02 ====')
dia = input('qual o dia do seu nascimento?')
mes = input('qual o mes do seu nascimento?')
ano = input('qual o ano do seu nascimento?')
print('Voce nasceu no dia ' + dia + ' de ' + mes + ' de ' + ano + '. Correto?')
